---
####AUDIT####
  - name: RedHat - dependency package [libselinux-python]
    yum: name=libselinux-python state=present
    failed_when: no
    when:
      - ansible_os_family == "RedHat"
    tags:
      - always

  - name: "Ensure custom fact directory exists"
    shell: "find /etc/ -name 'ansible'"
    register: find
    tags:
      - factcustomdir

  - name: "Ensure custom fact directory exists"
    file:
      path=/etc/ansible/facts.d
      recurse=yes
      state=directory
    when: find.stdout == ""
    tags:
      - factcustomdir

  - name: "Transfering custom fact files for centos7"
    template:
      src: "{{ item }}"
      dest: /etc/ansible/facts.d/
      mode: 0755
    with_fileglob:
      - ../templates/audit/centos7/*.fact
    when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    tags:
      - centos
      - centos7
