---
####AUDIT####
  - name: Ensure custom fact directory exists
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
    with_items:
      - /etc/ansible
      - /etc/ansible/facts.d
    tags:
      - always

  - name: "Transfering custom fact files for centos7"
    template:
      src: "{{ item }}"
      dest: /etc/ansible/facts.d/
      mode: 0755
    with_fileglob:
      - ../templates/audit/centos7/*.fact
    when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    tags:
      - centos
      - centos7
