---
####DB####
  - name: creating database
    postgresql_db:
      name: cis
    become_user: postgres
    run_once: true
    when: inventory_hostname in (groups['localhost'] | default([]))

  - name: creating db table and columns
    postgresql_table:
      db: cis
      name: linuxos
      columns:
      - id SERIAL PRIMARY KEY
      - created_at TIMESTAMP DEFAULT NOW()
      - hostname VARCHAR(100) NOT NULL
      - ipaddress VARCHAR(100) NOT NULL
      - tag_name VARCHAR(100) NOT NULL
      - values VARCHAR(70) NOT NULL
    become_user: postgres
    when: inventory_hostname in (groups['localhost'] | default([]))
    run_once: true

  - name: copying facts into table
    postgresql_query:
      db: cis
      query: COPY linuxos(hostname,ipaddress,values) from PROGRAM 'cat /var/lib/pgsql/cisfacts/*' delimiter '|'
    become_user: postgres
    run_once: true
    delegate_to: localhost
