---
# tasks file for sample_cis
- include: backup.yml
  tags:
    - centos
    - centos7

####AUDIT####
- include: audit.yml
  tags:
    - centos
    - centos7

####ACTUALFACT####
- include: actualfact_centos7.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - actualfact
    - centos
    - centos7
    - db

####RELOADINGFACT####
- name: reloading ansible_local
  setup: filter=ansible_local
  tags:
    - always

####DB####
- include: db.yml
  tags:
    - db
    - never

####REMEDY####
- include: centos7.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - centos
    - centos7
    - remedy
    - db

####RELOADINGFACT####
- name: reloading ansible_local
  setup: filter=ansible_local
  tags:
    - always
